node_rate_loop: 30
width: 1600
height: 600
quality: 50
auto_exposure: true
exposure_value: 15
auto_wb: false
auto_wb_compensation: false
red_gain: 10
blue_gain: 50


# mode: 7, 1600x600
# mode: 8, 2560x720
# mode: 9, 3840x1080
# mode: 10, 5184x1944
# mode: 11, 6528x1848
# mode: 12, 6528x2464